name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # update per jam
  workflow_dispatch: # bisa manual
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_anilist: yes
          plugin_anilist_user: chestaazka
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_leetcode: yes
          plugin_leetcode_user: chestaazka
          plugin_leetcode_sections: solved, skills, recent
          plugin_terminal: yes
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
